// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBzxAFBppxBUxf4luBCifyh_Q04vnEjgo',
    appId: '1:637717472637:web:d4f2eb456b966fcb329814',
    messagingSenderId: '637717472637',
    projectId: 'bookshop-57c0b',
    authDomain: 'bookshop-57c0b.firebaseapp.com',
    storageBucket: 'bookshop-57c0b.appspot.com',
    measurementId: 'G-87QJHGRTLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAutE4-opuIFY9T11kq24nyfJa_uodlNU',
    appId: '1:637717472637:android:5743e96767237c23329814',
    messagingSenderId: '637717472637',
    projectId: 'bookshop-57c0b',
    storageBucket: 'bookshop-57c0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgIqP4PfAevVo7B-Yqj8c29rqF9JB6N_o',
    appId: '1:637717472637:ios:62ed43f604b7ce3e329814',
    messagingSenderId: '637717472637',
    projectId: 'bookshop-57c0b',
    storageBucket: 'bookshop-57c0b.appspot.com',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgIqP4PfAevVo7B-Yqj8c29rqF9JB6N_o',
    appId: '1:637717472637:ios:3a123a209e3cb70b329814',
    messagingSenderId: '637717472637',
    projectId: 'bookshop-57c0b',
    storageBucket: 'bookshop-57c0b.appspot.com',
    iosBundleId: 'com.example.bookly.RunnerTests',
  );
}
